#ifndef TESTS_H
#define TESTS_H

#include "canvas.h"
#include "color.h"
#include "intersection.h"
#include "light_source.h"
#include "matrix.h"
#include "ray.h"
#include "sphere.h"
#include "tuple.h"
#include "utilities.h"
#include <cmath>
#include <iostream>
#include <ostream>
#include <sstream>
#include <cassert>

void test_tuple_to_point();
void test_tuple_to_vector();
void test_tuple_addition();
void test_point_minus_point();
void test_point_minus_vector();
void test_subtract_vector_from_zero_vector();
void test_negate_tuple();
void test_multiply_tuple_by_scalar();
void test_divide_tuple_by_scalar();
void test_magnitude_of_vector();
void test_normalize_vector();
void test_dot_product_vector();
void test_cross_product_vector();
void test_color_implementation();
void test_color_addition();
void test_color_subtraction();
void test_color_multiplication_by_scalar();
void test_color_multiply_by_color();
void test_create_canvas();
void test_writing_canvas();
void test_canvas_to_ppm_header();
void test_matrix_construction();
void test_matrix_comparision_equal();
void test_matrix_comparision_not_equal();
void test_matrix_multiply();
void test_matrix_tuple_multiply();
void test_identity_matrix_multiplication();
void test_matrix_transpose();
void test_matrix_submatrix();
void test_matrix_determinant_2x2();
void test_matrix_minor_3x3();
void test_matrix_cofactor();
void test_matrix_determinant_large();
void test_matrix_inversion();
void test_matrix_translation();
void test_matrix_scaling();
void test_matrix_rotation_x();
void test_matrix_rotation_x_inverse();
void test_matrix_rotation_y();
void test_matrix_rotation_z();
void test_matrix_shearing();
void test_individual_and_chained_transformations();
void test_create_and_query_ray();
void test_ray_point_from_dist();
void test_sphere_ray_intersect_at_two_points();
void test_sphere_ray_intersect_at_tangent();
void test_sphere_ray_miss();
void test_sphere_behind_ray();
void test_hit_all_positive_t();
void test_hit_some_negative_t();
void test_hit_all_negative_t();
void test_hit_lowest_non_negative_t();
void test_translating_a_ray();
void test_scaling_a_ray();
void test_sphere_default_transformation();
void test_sphere_transformation();
void test_intersect_scaled_sphere_with_ray();
void test_intersect_translated_sphere_with_ray();
void test_normal_on_sphere_at_point_on_x_axis();
void test_normal_on_sphere_at_point_on_y_axis();
void test_normal_on_sphere_at_point_on_z_axis();
void test_normal_on_sphere_at_non_axial_point();
void test_normal_is_a_normalized_vector();
void test_computing_normal_on_translated_sphere();
void test_computing_normal_on_transformed_sphere();
void test_reflecting_a_vector_approaching_at_45_degrees();
void test_reflecting_a_vector_off_a_slanted_surface();
void test_point_light_source();
void test_default_material();
void test_sphere_has_default_material();
void test_sphere_may_be_assigned_a_material();
void test_lighting_with_eye_between_light_and_surface();
void test_lighting_with_eye_between_light_and_surface_eye_offset_45_degrees();
void test_lighting_with_eye_opposite_surface_light_offset_45_degrees();
void test_lighting_with_eye_in_the_path_of_the_reflection_vector();
void test_lighting_with_the_light_behind_the_surface();
void test_world_empty_on_creation();
void test_default_world();
void test_intersect_world_with_ray();
void test_precomputing_state_of_intersection();
void test_precomputing_state_of_intersection_inside();
void test_shading_an_intersection();
void test_shading_an_intersection_from_the_inside();
void test_color_at_ray_misses();
void test_color_at_ray_hits();
void test_color_with_intersection_behind_the_ray();
void test_view_transformation_default();
void test_view_transformation_positive_z();
void test_view_transformation_translation();
void test_pixel_size_horizontal();
void test_pixel_size_vertical();
void test_ray_through_center_of_canvas();
void test_ray_through_corner_of_canvas();
void test_ray_with_transformed_camera();
void test_rendering_a_world_with_a_camera();
void test_lighting_with_surface_in_shadow();
void test_no_shadow_collinear_point_and_light();
void test_is_shadowed_with_obstruction();
void test_is_shadowed_object_behind_light();
void test_is_shadowed_object_behind_point();
void test_hit_offset_point();
void test_default_shape_transformation();
void test_assigning_a_transformation_on_base_shape();
void test_default_shape_has_default_material();
void test_assigning_a_material_to_a_shape();
void test_shape_intersection_encapsulates_material();
void test_intersecting_a_scaled_shape_with_a_ray();
void test_intersecting_a_translated_shape_with_a_ray();
void test_computing_the_normal_on_a_translated_shape();
void test_computing_the_normal_on_a_transformed_shape();
void test_the_normal_of_a_plane_is_constant_everywhere();
void test_intersect_with_a_ray_parallel_to_the_plane();
void test_intersect_with_a_coplanar_ray();
void test_a_ray_intersecting_a_plane_from_above();
void test_a_ray_intersecting_a_plane_from_below();
void test_create_stripe_pattern();
void test_stripe_pattern_is_constant_in_y();
void test_stripe_pattern_is_constant_in_z();
void test_stripe_pattern_alternates_in_x();
void test_lightning_with_pattern_applied();
void test_stripe_pattern_with_object_transformation();
void test_stripe_pattern_with_pattern_transformation();
void test_stripe_pattern_with_both_transformations();
void test_default_pattern_transformation();
void test_assigning_a_transformation();
void test_pattern_with_an_object_transformation();
void test_pattern_with_a_pattern_transformation();
void test_pattern_with_both_transformations();
void test_gradient_pattern_interpolates();
void test_ring_pattern_alternates_in_both_x_and_z();
void test_checkers_pattern_alternates_in_x();
void test_checkers_pattern_alternates_in_y();
void test_checkers_pattern_alternates_in_z();
void test_reflectivity_for_default_material();
void test_precomupting_reflection_vector();
void test_reflected_color_for_nonreflective_material();
void test_reflected_color_for_reflective_material();
void test_shade_hit_with_reflective_material();
void test_reflected_color_prevents_infinite_recursion();
void test_transparency_and_refractive_index_for_default_material();
void test_glass_sphere_init();
void test_finding_n1_and_n2_at_various_intersections();
void test_under_point_offset_precomputation();
void test_refracted_color_of_opaque_surface_is_black();
void test_refracted_color_under_total_internal_reflection();
void test_refracted_color_with_a_refracted_ray();
void test_shade_hit_with_a_transparent_material();
void test_schlick_approximation_under_total_internal_reflection();
void test_schlick_approximation_with_a_perpendicular_viewing_angle();
void test_schlick_approximation_with_a_grazing_angle();
void test_shade_hit_with_a_reflective_transparent_material();
void test_check_axis_behavior();
void test_cube_intersections();
void test_cube_normals();
void test_ray_misses_a_cylinder();
void test_ray_strikes_a_cylinder();
void test_normal_vector_on_a_cylinder();
void test_default_minimum_and_maximum();
void test_intersecting_a_constrained_cylinder();
void test_default_closed_value();
void test_intersecting_caps_of_a_closed_cylinder();
void test_normal_vector_on_a_cylinders_end_caps();
void test_intersecting_a_cone_with_a_ray();
void test_intersecting_cone_with_ray_parallel_to_one_half();
void test_intersecting_a_cones_end_caps();
void test_computing_the_normal_vector_on_a_cone();

#endif
